#!/bin/bash

# $Id: runJobConditionally,v 1.3 2016/02/27 17:41:18 aosorio Exp $
#
# Script para ejecutar el backup de un cliente sólo si está despierto.
#

job=$1
client=$2
port=$3

if [ "x$1" == "x" ] || [ "x$2" == "x" ] ; then
  cat <<FFAA
Modo de uso

  $0 <job> <client> [<port>]

  job    Trabajo a ejecutar.
  client Dirección del cliente.
  port   Puerto donde escucha el cliente de Bacula.
FFAA

  exit 2
fi

/etc/bacula/scripts/client_is_online $client $port && {
  echo run job=$job yes | bconsole > /dev/null
  sleep 3
  echo wait job=$job | bconsole > /dev/null
  exit 0
} || {
  echo "El cliente no está online."
  exit 2
}
